name: review_marketplace
description: A Flutter app for review marketplace

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  # Firebase
  firebase_core: ^2.24.2
  firebase_auth: ^4.15.3
  cloud_firestore: ^4.13.6
  firebase_storage: ^11.5.6
  firebase_messaging: ^14.7.10
  cloud_functions: ^4.6.6

  # State Management
  get: ^4.6.6

  # UI & Navigation
  cupertino_icons: ^1.0.2
#  flutter_launcher_icons: ^0.13.1

  # Image & Media
  image_picker: ^1.0.4
  cached_network_image: ^3.3.0

  # Payments
  razorpay_flutter: ^1.3.5
#  upi_india: ^3.0.1

  # Utilities
  intl: ^0.18.1
  shared_preferences: ^2.2.2
  connectivity_plus: ^5.0.2
  permission_handler: ^11.1.0

  # HTTP & Networking
  http: ^1.1.0

  # Local Notifications
#  flutter_local_notifications: ^16.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/